export const GET_ALL_USERS = "GET_ALL_USERS"
export const DELETE_USER = "DELETE_USER"

export const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS"
export const GET_BOOKINGS_BY_ID = "GET_BOOKINGS_BY_ID"
export const GET_BOOKINGS_BY_USER = "GET_BOOKINGS_BY_USER";

export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS"
export const ADD_FLIGHT = "ADD_FLIGHT"
export const DELETE_FLIGHT = "DELETE_FLIGHT"
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";

export const GET_ALL_AIRPORTS = "GET_ALL_AIRPORTS"