export const GET_ALL_AIRPORTS = "GET_ALL_AIRPORTS"
export const GET_BOOKINGS_BY_USER = "GET_BOOKINGS_BY_USER"

export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS"
export const GET_FLIGHT_DETAILS = "GET_FLIGHT_DETAILS"
export const GET_FLIGHT_BY_ID = "GET_FLIGHT_BY_ID"
export const ADD_BOOKING = "ADD_BOOKING"
export const USER_FLIGHT_BOOKING = "USER_FLIGHT_BOOKING"