export const GET_USER_BY_NAME = "GET_USER_BY_NAME"
export const UPDATE_USER = "UPDATE_USER"

export const ADD_BOOKING="ADD_BOOKING"
export const GET_BOOKINGS_BY_USER="GET_BOOKINGS_BY_USER"

export const GET_FLIGHTS_BY_ROUTE = "GET_FLIGHTS_BY_ROUTE"
export const GET_FLIGHTS_BY_DATE = "GET_FLIGHTS_BY_DATE"